version: 2.1
orbs:
    rust: glotrade/rust@0.1.3
workflows:
    default:
        jobs:
            - rust/check:
                  toolchain: nightly
            - rust/clippy:
                  toolchain: nightly
            - rust/format
            - rust/test:
                  toolchain: nightly
